[package]
name = "celer-devtool"
version = "2.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
celer-lib = { path = "../celer-lib" }
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8.23"
linked-hash-map = "0.5.4"
tungstenite = "0.17.2"
ctrlc = "3.2.2"
chrono = "0.4.19"
clap = { version = "3.2.17", features = ["derive"] }
panic-message = "0.3.0"
const_format = "0.2.26"
