# codegen include github-actions.common.include
name: Push

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
codegen begin
DefineJobStart check,Health Check,ubuntu-latest,#
CommonSetup
JustCIJob check
codegen end

codegen begin
DefineJobStart rs-lint,Lint RS,ubuntu-latest,#
CommonSetup
JustCIJob rs-lint
codegen end

codegen begin
DefineJobStart ts-lint,Lint TS,ubuntu-latest,#
CommonSetup
SetupNode
JustCIJob ts-lint
codegen end

codegen begin
DefineJobStart run-unit-test,Unit Test,ubuntu-latest,#
CommonSetup
SetupNode
JustCIJob unit-test
codegen end

codegen begin
DefineJobStart e2e-test,Devtool E2E Test,${{ matrix.os }},strategy: { matrix: { os: [ ubuntu-latest\, macos-latest ] } }
CommonSetup
JustCIJob e2e-test
codegen end

codegen begin
DefineJobStart e2e-test-windows,Devtool E2E Test for Windows,windows-latest,#
SetWindowsLineEnd
CommonSetup
JustCIJob e2e-test-windows
codegen end

codegen begin
DefineJobStart cargo-build-ubuntu,Build Devtool (Ubuntu),ubuntu-latest,#
CommonSetup
JustCIJob cargo-release
JustCIJob cargo-tar-ubuntu
UploadArtifact cdt-ubuntu,release-ci/celer-devtool-x86_64-linux.tar.gz
codegen end

codegen begin
DefineJobStart cargo-build-macos,Build Devtool (Mac OS),macos-latest,#
CommonSetup
JustCIJob cargo-release
JustCIJob cargo-tar-macos
UploadArtifact cdt-macos,release-ci/celer-devtool-x86_64-darwin.tar.gz
codegen end

codegen begin
DefineJobStart cargo-build-windows,Build Devtool (Windows),windows-latest,#
CommonSetup
JustCIJob cargo-release
JustCIJob cargo-tar-windows
UploadArtifact cdt-windows,release-ci/celer-devtool-x86_64-windows.tar.gz
codegen end

codegen begin
DefineJobStart web-build,Build Web,ubuntu-latest,#
CommonSetup
SetupNode
SetupWasmPack
SkipJobWIP web-test
JustCIJob web-build
JustCIJob web-tar
UploadArtifact cwa,release-ci/celer-web-app.tar.gz
codegen end

codegen begin
DefineJobStart vsce-build,Build VSCE,ubuntu-latest,#
CommonSetup
SetupNode
JustCIJob vsce-build
JustCIJob vsix
UploadArtifact vsix,release-ci/celer.vsix
codegen end

codegen begin
DefineJobStart wiki-build,Build Wiki,ubuntu-latest,#
CommonSetup
JustCIJob wiki-release
codegen end
