# codegen include github-actions.common.include
name: Forward to Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
codegen begin
DefineJobStart check,Health Check,ubuntu-latest,#
JustCIJob check
codegen end
# Skip linting RS and TS

codegen begin
DefineJobStart cargo-build-ubuntu,Build Devtool (Ubuntu),ubuntu-latest,#
JustCIJob cargo-release
JustCIJob cargo-tar-ubuntu
UploadArtifact cdt-ubuntu,release-ci/celer-devtool-x86_64-linux.tar.gz
codegen end

codegen begin
DefineJobStart cargo-build-macos,Build Devtool (Mac OS),macos-latest,#
JustCIJob cargo-release
JustCIJob cargo-tar-macos
UploadArtifact cdt-macos,release-ci/celer-devtool-x86_64-darwin.tar.gz
codegen end

codegen begin
DefineJobStart cargo-build-windows,Build Devtool (Windows),windows-latest,#
JustCIJob cargo-release
JustCIJob cargo-tar-windows
UploadArtifact cdt-windows,release-ci/celer-devtool-x86_64-windows.tar.gz
codegen end

codegen begin
DefineJobStart web-build,Build Web,ubuntu-latest,#
SetupNode
SkipJobWIP web-test
JustCIJob web-build
JustCIJob web-tar
UploadArtifact cwa,release-ci/celer-web-app.tar.gz
codegen end

codegen begin
DefineJobStart vsce-build,Build VSCE,ubuntu-latest,#
SetupNode
JustCIJob vsce-build
JustCIJob vsix
UploadArtifact vsix,release-ci/celer.vsix 
codegen end
