# codegen include github-actions.common.include
name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
codegen begin
DefineJobStart check,Health Check,ubuntu-latest,#
JustCIJob check
codegen end

codegen begin
DefineJobStart rs-lint,Lint RS,ubuntu-latest,#
JustCIJob rs-lint
codegen end

codegen begin
DefineJobStart ts-lint,Lint TS,ubuntu-latest,#
SetupNode
JustCIJob ts-lint
codegen end

codegen begin
DefineJobStart run-unit-test,Unit Test,ubuntu-latest,#
JustCIJob unit-test
codegen end

codegen begin
DefineJobStart cargo-build,Build Devtool,${{ matrix.os }},strategy: { matrix: { os: [ ubuntu-latest\, macos-latest\, windows-latest ] } }
JustCIJob cargo
codegen end

codegen begin
DefineJobStart e2e-test,Devtool E2E Test,${{ matrix.os }},strategy: { matrix: { os: [ ubuntu-latest\, macos-latest ] } }
JustCIJob e2e-test
codegen end

codegen begin
DefineJobStart e2e-test-windows,Devtool E2E Test for Windows,windows-latest,#
JustCIJob e2e-test-windows
codegen end

codegen begin
DefineJobStart web-build,Build Web,ubuntu-latest,#
SetupNode
SetupWasmPack
JustCIJob web-build
codegen end

codegen begin
DefineJobStart vsce-build,Build VSCE,ubuntu-latest,#
SetupNode
JustCIJob vsce-build
codegen end
