[package]
name = "celer-lib"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "celer"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.79"
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
