[package]
name = "celer-lib"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "celer"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "=0.2.81", features = ["serde-serialize"]}
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0"
base64 = "0.13.0"
flate2 = "1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
