[[celer-web-app]]
file="packages/celer-web-app/package.json"
line=4
char=14
end='"'

[[celer-web-app]]
file="packages/celer-web-app/CHANGELOG.md"
line=4
char=4
end="`"

[[celer-web-app]]
file="packages/celer-web-app/src/data/util/version.ts"
line=1
char=30
end='"'

[[celer-vscode-extension]]
file="packages/celer-vscode-extension/package.json"
line=5
char=16
end='"'

[[celer-vscode-extension]]
file="packages/celer-vscode-extension/CHANGELOG.md"
line=4
char=4
end="`"

[[celer-vscode-extension]]
file="packages/celer-vscode-extension/README.md"
line=19
char=4
end="`"

[[celer-devtool]]
file="packages/celer-devtool/CHANGELOG.md"
line=4
char=4
end="`"

[[celer-devtool]]
file="packages/celer-devtool/Cargo.toml"
line=3
char=11
end='"'

[[celer-devtool]]
file="packages/celer-devtool/src/main.rs"
line=6
char=27
end='"'

[[celer-devtool]]
file="packages/celer-e2e-test/tests/version/version.txt"
line=1
char=14
end=""

[[celer-devtool]]
file="packages/celer-e2e-test/tests/version/long_version.txt"
line=1
char=14
end=" "

[[celer-lib]]
file="packages/celer-lib/CHANGELOG.md"
line=4
char=4
end="`"

[[celer-lib]]
file="packages/celer-lib/Cargo.toml"
line=3
char=11
end='"'

[[celer-lib]]
file="packages/celer-lib/src/lib.rs"
line=8
char=27
end='"'

[[celer-lib]]
file="packages/celer-e2e-test/tests/version/long_version.txt"
line=1
char=25
end=")"
