import { CelerPreset } from "./Preset";

export class ShrinePreset implements CelerPreset {
	hasMember(): boolean {
		return true;
	}
	getPrimaryClass(): string {
		return "Shrine";
	}
	registerEnums(register: (name: string, description: string, subclass?: string, isSubNamespace?: boolean) => void): void {
		// Generated Code
		register("JaBaij", "Ja Baij Shrine");
		register("OmanAu", "Oman Au Shrine");
		register("OwaDaim", "Owa Daim Shrine");
		register("KehNamut", "Keh Namut Shrine");
		register("AkhVaquot", "Akh Va'quot Shrine");
		register("BereedaNaag", "Bereeda Naag Shrine");
		register("BoshKala", "Bosh Kala Shrine");
		register("ChaasQeta", "(modest/major ToS) Chaas Qeta Shrine");
		register("DaagChokah", "(blessing) Daag Chokah Shrine");
		register("DagahKeek", "(blessing) Dagah Keek Shrine");
		register("DahHesho", "(minor ToS) Dah Hesho Shrine");
		register("DahKaso", "(minor ToS) Dah Kaso Shrine");
		register("DakaTuss", "Daka Tuss Shrine");
		register("DaqaKoh", "Daqa Koh Shrine");
		register("DaqoChisay", "Daqo Chisay Shrine");
		register("DaqoTah", "Daqo Tah Shrine");
		register("DilaMaag", "(blessing) Dila Maag Shrine");
		register("DowNaeh", "Dow Na'eh Shrine");
		register("DunbaTaag", "Dunba Taag Shrine");
		register("EtsuKorima", "(DLC) Etsu Korima Shrine");
		register("GeeHarah", "Gee Ha'rah Shrine");
		register("GomaAsaagh", "(modest/major ToS) Goma Asaagh Shrine");
		register("GoraeTorr", "(blessing) Gorae Torr Shrine");
		register("HaDahamar", "Ha Dahamar Shrine");
		register("HawaKoth", "Hawa Koth Shrine");
		register("HiaMiu", "(modest/major ToS) Hia Miu Shrine");
		register("HilaRao", "Hila Rao Shrine");
		register("IshtoSoh", "Ishto Soh Shrine");
		register("JeeNoh", "Jee Noh Shrine");
		register("JitanSami", "(blessing) Jitan Sa'mi Shrine");
		register("JolooNah", "Joloo Nah Shrine");
		register("KaamYatak", "Kaam Ya'tak Shrine");
		register("KahMael", "Kah Mael Shrine");
		register("KahOkeo", "Kah Okeo Shrine");
		register("KahYah", "Kah Yah Shrine");
		register("KamUrog", "Kam Urog Shrine");
		register("KamiaOmuna", "(DLC) Kamia Omuna Shrine");
		register("KaoMakagh", "Ka'o Makagh Shrine");
		register("KatahChuki", "(minor ToS) Katah Chuki Shrine");
		register("KatosaAug", "Katosa Aug Shrine");
		register("KayNoh", "Kay Noh Shrine");
		register("KayaWan", "Kaya Wan Shrine");
		register("KayraMah", "Kayra Mah Shrine");
		register("KeeDafunia", "(DLC) Kee Dafunia Shrine");
		register("KeehaYoog", "(blessing) Keeha Yoog Shrine");
		register("KeiveTala", "(DLC) Keive Tala Shrine");
		register("KemaKossasa", "(modest/major ToS) Kema Kossasa Shrine");
		register("KemaZoos", "Kema Zoos Shrine");
		register("KenaiShakah", "(modest/major ToS) Ke'nai Shakah Shrine");
		register("KeoRuug", "Keo Ruug Shrine");
		register("KetohWawai", "(blessing) Ketoh Wawai Shrine");
		register("KiahToza", "(DLC) Kiah Toza Shrine");
		register("KihiroMoh", "(DLC) Kihiro Moh Shrine");
		register("KorguChideh", "(blessing) Korgu Chideh Shrine");
		register("KorshOhu", "(blessing) Korsh O'hu Shrine");
		register("KuhTakkar", "Kuh Takkar Shrine");
		register("KuhnSidajj", "(blessing) Kuhn Sidajj Shrine");
		register("LaknaRokee", "(blessing) Lakna Rokee Shrine");
		register("LannoKooh", "(blessing) Lanno Kooh Shrine");
		register("MaagHalan", "(blessing) Maag Halan Shrine");
		register("MaagNorah", "(blessing) Maag No'rah Shrine");
		register("MahEliya", "(DLC) Mah Eliya Shrine");
		register("MakaRah", "Maka Rah Shrine");
		register("MezzaLo", "Mezza Lo Shrine");
		register("MijahRokee", "(modest/major ToS) Mijah Rokee Shrine");
		register("MirroShaz", "Mirro Shaz Shrine");
		register("MisaeSuma", "(blessing) Misae Suma Shrine");
		register("MoaKeet", "Mo'a Keet Shrine");
		register("MoggLatan", "Mogg Latan Shrine");
		register("MonyaToma", "Monya Toma Shrine");
		register("MozoShenno", "(modest/major ToS) Mozo Shenno Shrine");
		register("MuwoJeem", "(modest/major ToS) Muwo Jeem Shrine");
		register("MyahmAgana", "Myahm Agana Shrine");
		register("NamikaOzz", "(modest/major ToS) Namika Ozz Shrine");
		register("NeezYohma", "Ne'ez Yohma Shrine");
		register("NoeRajee", "(DLC) Noe Rajee Shrine");
		register("NoyaNeha", "(minor ToS) Noya Neha Shrine");
		register("PumaagNitae", "(minor ToS) Pumaag Nitae Shrine");
		register("QazaTokki", "(blessing) Qaza Tokki Shrine");
		register("QuaRaym", "Qua Raym Shrine");
		register("QukahNata", "(blessing) Qukah Nata Shrine");
		register("RaqaZunzo", "(blessing) Raqa Zunzo Shrine");
		register("ReeDahee", "Ree Dahee Shrine");
		register("RinOyaa", "Rin Oyaa Shrine");
		register("RinuHonika", "(DLC) Rinu Honika Shrine");
		register("RitaagZumo", "(blessing) Ritaag Zumo Shrine");
		register("RohtaChigah", "(DLC) Rohta Chigah Shrine");
		register("RokUwog", "Rok Uwog Shrine");
		register("RonaKachta", "(blessing) Rona Kachta Shrine");
		register("RotaOoh", "Rota Ooh Shrine");
		register("RuccoMaag", "Rucco Maag Shrine");
		register("RuvoKorbah", "(DLC) Ruvo Korbah Shrine");
		register("SaasKosah", "(modest/major ToS) Saas Ko'sah Shrine");
		register("SahDahaj", "Sah Dahaj Shrine");
		register("SasaKai", "(modest/major ToS) Sasa Kai Shrine");
		register("SatoKoda", "(DLC) Sato Koda Shrine");
		register("ShaGehma", "Sha Gehma Shrine");
		register("ShaWarvo", "Sha Warvo Shrine");
		register("ShadaNaw", "Shada Naw Shrine");
		register("ShaeKatha", "(blessing) Shae Katha Shrine");
		register("ShaeLoya", "Shae Loya Shrine");
		register("ShaeMosah", "Shae Mo'sah Shrine");
		register("ShaiUtoh", "Shai Utoh Shrine");
		register("ShaiYota", "(blessing) Shai Yota Shrine");
		register("SharoLun", "(DLC) Sharo Lun Shrine");
		register("SheeVaneer", "Shee Vaneer Shrine");
		register("SheeVaneth", "Shee Vaneth Shrine");
		register("SheemDagoze", "Sheem Dagoze Shrine");
		register("ShehRata", "Sheh Rata Shrine");
		register("ShiraGomar", "(DLC) Shira Gomar Shrine");
		register("ShoDantu", "Sho Dantu Shrine");
		register("ShodaSah", "Shoda Sah Shrine");
		register("ShoqaTatone", "(modest/major ToS) Shoqa Tatone Shrine");
		register("ShoraHah", "Shora Hah Shrine");
		register("SohKofi", "(minor ToS) Soh Kofi Shrine");
		register("SumaSahma", "(blessing) Suma Sahma Shrine");
		register("TahMuhl", "Tah Muhl Shrine");
		register("TakamaShiri", "(DLC) Takama Shiri Shrine");
		register("TalohNaeg", "(minor ToS) Ta'loh Naeg Shrine");
		register("TalohOah", "(blessing) Taloh O'ah Shrine");
		register("TawaJinn", "(blessing) Tawa Jinn Shrine");
		register("TenaKosah", "(modest/major ToS) Tena Ko'sah Shrine");
		register("ThoKayu", "(blessing) Tho Kayu Shrine");
		register("ToQuomo", "(blessing) To Quomo Shrine");
		register("TohYahsa", "Toh Yahsa Shrine");
		register("TotoSah", "Toto Sah Shrine");
		register("TuKaloh", "(blessing) Tu Ka'loh Shrine");
		register("TutsuwaNima", "(modest/major ToS) Tutsuwa Nima Shrine");
		register("VooLota", "Voo Lota Shrine");
		register("WahgoKatta", "Wahgo Katta Shrine");
		register("YaNaga", "Ya Naga Shrine");
		register("YahRin", "Yah Rin Shrine");
		register("YowakaIta", "(DLC) Yowaka Ita Shrine");
		register("ZaltaWa", "Zalta Wa Shrine");
		register("ZeKasho", "Ze Kasho Shrine");
		register("ZunaKai", "(blessing) Zuna Kai Shrine");
	}
	getDocumentation(): string {
		return "The Shrine namespace contains a preset for each shrine in BOTW. Each preset defines the name, type, coordinate, icon, and time-override for the shrine. Also adds a comment to check korok count";
	}
}
