[package]
name = "celer-cli"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
celer-lib = { path = "../celer-lib" }
yaml-rust = "0.4"
linked-hash-map = "0.5.4"
